[phases.setup]
nixPkgs = ["nodejs-18_x"]
aptPkgs = ["git"]

[phases.install]
cmds = [
    "npm install -g npm@9.8.1",
    "npm config set engine-strict false",
    "npm install --legacy-peer-deps"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NODE_VERSION = "18.x"
NPM_CONFIG_PRODUCTION = "false" 