[phases.setup]
nixPkgs = ["nodejs"]
aptPkgs = ["git"]

[phases.install]
cmds = [
    "npm install -g npm@latest",
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false" 