[build]
builder = "nixpacks"
buildCommand = "npm install && cd frontend && CI=false npm install && npm run build"

[deploy]
startCommand = "cd backend && npm install && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100 